### ISSUE TITLE
click on marker does not show infowindow vaadin 7.4.2 firefox chrome

### ISSUE THREAD

**Issue by bedinsky** [tjkaal/GoogleMapsVaadin7#23]
Hi, sorry for this annoying iusse!
It seems that after clicking on marker, associated infowindow is showed only after mouse is moved away from marker. I mean infowindow is not showed unless mouse is moved that is a bit frustrating for a user.
I can figure out the reason of such behavoiur so I'm asking you any clue.
Regards

**Comment by tjkaal** [comment]
Could you please specify a bit? So you're facing this issue on both Chrome and Firefox browsers? Which OS and which version? Are you getting the same issue on the [online demo](http://tapio.app.fi/googlemaps/), when clicking on the marker in the middle (the one pointing to Kakola prison)?

**Comment by bedinsky** [comment]
Hi !  It might depend on OS, I'm using Mac OSX yosemite and I've seen the problem also with online demo. I got the iussue both with firefox and chrome browser latest versions. 
Only the very first time I clicked on Kakola, infowindow showed immediately.
I tried other times and infowindow showed up only if mouse pointer was moved away from marker.
Let me know if you have any clue.

**Comment by ossd** [comment]
HI, the same issue with Vaadin 7.5.2 Add-on Version 1.1.2  and Safari 8.0.7. If you click the marker nothing happens. If you then move the cursor, the event ist fired. Any suggestions?

**Comment by ossd** [comment]
Also the same behavior with Firefox and Chrome on Mac OS X 10.10.4

**Comment by ultraxion** [comment]
Hi, same issue... No workaround or plan to fix it ?

**Comment by fakeh** [comment]
Thanks for the addon, which I've been using for years at a lower version. 

Now I've updated, I'm getting this too.
Latest Firefox, Edge, Chrome and Safari all have the same problem, also on the online demo.

Is anyone not getting it?
Thanks,
Dan.

**Comment by tjkaal** [comment]
For some reason some browsers need 'something extra' to happen in order to cause the click event. I tried disabling dragging of the markers but this didn't affect them in any way.

Instead, if I changed marker#addClickHandler to marker#addMouseUpHandler, the info windows opened immediately. But now there's a new problem: if the marker is draggable and there's an info window bound to it, after a drag the info window opens. 

I don't want to waste anymore time with this, so I guess I'll just add a small timer that checks how long the mouse has been pressed and if it's enough (say more than 50 ms or something), the info window won't be opened and it will be considered as a drag instead.

**Comment by tjkaal** [comment]
Seems that 50 ms is a too little value while 500 ms is too much. My next guess is 150 ms, we'll see...

**Comment by tjkaal** [comment]
Yeah, for some reason adding click listeners work really weird on FireFox. Thus I'm doing it manually as I mentioned: when mouse goes down on a marker, a timer is started. If mouse gets up before 150 milliseconds are gone, it's considered a click and (possible) info window is opened. In any case, if the marker is moved, it's always considered a drag.

A new version with this fix will be released today. Please report any issues either here or as new tickets.
